# Generated by Django 3.1.7 on 2021-04-03 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('polls', '0003_auto_20210403_1810'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MarkPolls',
            new_name='MarkPoll',
        ),
    ]
