# Generated by Django 3.1.7 on 2021-04-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20210403_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='question_id',
        ),
        migrations.AddField(
            model_name='test',
            name='question_id',
            field=models.ManyToManyField(to='polls.Question'),
        ),
    ]
