# Generated by Django 3.1.7 on 2021-04-03 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20210403_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='amount_question',
        ),
    ]
