# Generated by Django 3.1.7 on 2021-04-03 19:13

import django.core.validators
from django.db import migrations, models
import homework.services.validate


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_homeworkanswer_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkanswer',
            name='answer',
            field=models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(['txt']), homework.services.validate.FileValidate.file_size]),
        ),
    ]
